workspace(name = "build_bazel_apple_support_tests")

local_repository(
    name = "build_bazel_apple_support",
    path = "../",
)

load(
    "@build_bazel_apple_support//lib:repositories.bzl",
    "apple_support_dependencies",
)

apple_support_dependencies()
