
matrix:
  include:
    # One build on linux to run buildifier since linux agents are faster on travis.
    - os: linux
      dist: trusty
      sudo: false
      language: c++
      env: BUILDIFIER=RELEASE


before_install:
  - ./travis_install.sh

script:
  - ./travis_test.sh

notifications:
  email: false

# Don't build the google branch since that is used by the export process and a PR
# will be made after the fact.
branches:
  except:
    - google
