load("@bazel_skylib//:bzl_library.bzl", "bzl_library")

licenses(["notice"])

package(default_visibility = ["//:__subpackages__"])

bzl_library(
    name = "providers",
    srcs = ["providers.bzl"],
)
