name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The new version to tag, ex: 1.0.5'
        required: true
        type: string
      branch:
        description: 'The branch to create the release off of'
        required: true
        type: string
        default: 'master'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}
      - name: Create Release
        run: |
          set -euo pipefail

          git config user.name "Automatic version bump"
          git config user.email "keithbsmiley@gmail.com"

          ./.github/update-module-version.sh "$TAG"
          tmp_branch="$(uuidgen)"
          git checkout -b "$tmp_branch"
          git add MODULE.bazel
          msg="Update MODULE.bazel to $TAG"
          git commit -m "$msg"
          git push -u origin "$tmp_branch"
          gh pr create --title "$msg" --body ""
          gh pr merge --auto --squash "$tmp_branch"

          COPYFILE_DISABLE=1 tar czvf "apple_support.$TAG.tar.gz" ./*
          ./.github/generate-notes.sh "$TAG" | tee notes.md
          gh release create "$TAG" --target "$BRANCH" --notes-file notes.md "apple_support.$TAG.tar.gz"
        env:
          TAG: ${{ inputs.tag }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ inputs.branch }}
